### PR TITLE
sphinx: pad out the starting packet with random bytes

### LINKED ISSUE #42: bug in Sphinx padding allows for last hop to learn the route length
I do not know if your use of the Sphinx packet format is such that variable length routes are used... however you should know that your Sphinx packet implementation does leak the route length to the last hop.

According to the recently submitted paper: Breaking and (Partially) Fixing Provably Secure Onion Routing, ( https://arxiv.org/abs/1910.13772 ) there is a padding bug where a sphinx implementation creates a header and in so doing uses zeros to pad the beta field whereas random data should be used instead because of the use of the stream cipher...

https://github.com/UCL-InfoSec/sphinx/blob/c05b7034eaffd8f98454e0619b0b1548a9fa0f42/SphinxClient.py#L67

```
# The os.urandom used to be a string of 0x00 bytes, but that's wrong
beta = dest + id + os.urandom(((2 * (p.r - nu) + 2)*p.k - len(dest)))
beta = p.xor(beta,
p.rho(p.hrho(asbtuples[nu-1]['s']))[:(2*(p.r-nu)+3)*p.k]) + phi
```

This bug, that is, if beta were padded with zeros instead of random bytes would allow
an adversary to determine the length of the route. This adversary would have to be the last hop and it could then XOR the beta portion of the header with zero bytes to learn how many skipped hops the Sphinx packet had.

### PR DESCRIPTION
**Pull request by Roasbeef**
By padding out the starting packet with random bytes rather than leaving
   the zeroes in tact, we patch a privacy leak that may reveal a lower
    bound on the true route length to an adversarial exit node.

  In order to reconcile this with our existing set of test vectors, we've
  introduced a new abstraction that allows the caller to specify how they
  want the starting bytes of the packet to be filled out. By default, all
  callers will use the `randPacketFiller`, but may also pass in the
  `blankPacketFiller`, if they packet construction to be deterministic.

Fixes #42.

### CODE REVIEW

File: sphinx.go [hunk 1]
```diff
@@ -206,6 +207,20 @@ func NewOnionPacket(paymentPath *PaymentPath, sessionKey *btcec.PrivateKey,
...
+	// Read out random bytes to fill out the rest of the starting packet
+	// after the hop payload for the final node. This mitigates a privacy
+	// leak that may reveal a lower bound on the true path length to the
+	// receiver.
+	//
+	// TODO(roasbeef): generate a rand stream using the session key
+	// instead?
+	firstHopSize := paymentPath[numHops-1].HopPayload.NumBytes()
+	randBytes := make([]byte, routingInfoSize-firstHopSize)
+	if _, err := rand.Read(randBytes[:]); err != nil {
```
Comment (cfromknecht) [inline sphinx.go]: read directly into `mixHeader[firstHopSize:]`, spares a large allocation and additional copying

File: sphinx.go [hunk 2]
```diff
@@ -206,6 +207,20 @@ func NewOnionPacket(paymentPath *PaymentPath, sessionKey *btcec.PrivateKey,
...
 	)
 
+	// Read out random bytes to fill out the rest of the starting packet
+	// after the hop payload for the final node. This mitigates a privacy
+	// leak that may reveal a lower bound on the true path length to the
+	// receiver.
+	//
+	// TODO(roasbeef): generate a rand stream using the session key
+	// instead?
+	firstHopSize := paymentPath[numHops-1].HopPayload.NumBytes()
```
Comment (cfromknecht) [inline sphinx.go]: return early if `numHops == 0` to prevent panic. previously the method would exit cleanly for zero-hop routes

**Comment by Roasbeef** [comment]
Latest push should now pass the build. We now require the caller specify a packet filler. In `lnd` and everywhere else, the `randomPacketFiller` should be used. For our test vectors, we're able to pass in a `blankPacketFiller` which doesn't actually do anything a (noop).

File: packetfiller.go [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+// PacketFiller is a function type to be specified by the caller to provide a
+// stream of random bytes derived from a CSPRNG to fill out the starting packet
+// in order to ensure we don't leak information on the true route length to the
+// receiver. The packet filler may also use the session key to generate a set
+// of filler bytes if it wishes to be deterministic.
+type PacketFiller func(*btcec.PrivateKey, *[routingInfoSize]byte) error
+
+// RandPacketFiller is a packet filler that reads a set of random bytes from a
+// CSPRNG.
+func RandPacketFiller4(_ *btcec.PrivateKey, mixHeader *[routingInfoSize]byte) error {
```
Comment (cfromknecht) [inline packetfiller.go]: remove trailing 4, or maybe remove entirely?

Comment (Roasbeef) [reply packetfiller.go]: Ah was left on in order to break compilation for areas that hadn't been updated. Removed.
